name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ connector-release-pipeline ]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-connector-template.yml@10.x-workflow-update
    secrets: inherit
    with:
      package-name: asb
      package-org: ballerinax
